services:
  app:
    build:
      context: ./project
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./project:/var/www
      - composer_vendor:/var/www/vendor
      - js_node_modules:/var/www/node_modules
volumes:
  composer_vendor:
  js_node_modules: